web/aidants365/urls.py
"""aidants365 URL Configuration
"""
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.views.static import serve
from . import views


urlpatterns = [
    path('', lambda req: redirect('fichier/')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('fichier/', include('fichier.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('media/fiches.pdf', views.protected_serve, {'document_url': settings.MEDIA_URL, 'document_root': settings.MEDIA_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "fichier.views.page_not_found_view"

web/fichier/urls.py
from django.urls import path, re_path

from . import views

from django.views.decorators.cache import cache_page

app_name = "fichier"

# durée cache par défaut
dcp = 2 * 60   # 2 mn
dcf = 15 * 60  # 15 mn
oneday = 60 * 60 * 24

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('rechercher/', views.rechercher, name='rechercher'),
    path('desk/', views.desk, name='desk'),
    path('desk/<int:id>/', views.document, name='document'),
    path('desk/<pk>/delete/', views.DeleteDocumentView.as_view(), name='document_delete'),
    path('fiches/', views.index, name='index'),
    path('fiches/<int:id>/', views.index_detail, name='index_detail'),
    path('fiche/<int:id>/', views.detail, name='detail'),
    path('fiche/<pk>/pdf/', views.FicheViewPDF.as_view(), name='detail_pdf'),
    path('fiche/<pk>/delete/', views.DeleteFicheView.as_view(), name='fiche_delete'),
    path('niveau/<int:id>/', views.index_niveau, name='index_niveau'),
    path('niveau/<int:id1>/<int:id2>/', views.index_niveau_detail, name='index_niveau_detail'),
    path('categories/', views.categories, name='categories'),
    path('categories/alpha/', views.categories_alpha, name='categories_alpha'),
    path('categories/nuage/', views.categories_nuage, name='categories_nuage'),
    path('categorie/<int:id>/', views.index_categorie, name='index_categorie'),
    path('categorie/<pk>/delete/', views.DeleteCategorieView.as_view(), name='categorie_delete'),
    path('categorie/<int:id1>/<int:id2>/', views.index_categorie_detail, name='index_categorie_detail'),
    path('auteur/<int:id>/', views.index_auteur, name='index_auteur'),
    path('auteur/<int:id1>/<int:id2>/', views.index_auteur_detail, name='index_auteur_detail'),
    path('themes/', views.themes, name='themes'),
    path('themes/alpha/', views.themes_alpha, name='themes_alpha'),
    path('themes/nuage/', views.themes_nuage, name='themes_nuage'),
    path('theme/<int:id>/', views.index_theme, name='index_theme'),
    path('theme/<int:id1>/<int:id2>/', views.index_theme_detail, name='index_theme_detail'),
    path('theme/<pk>/delete/', views.DeleteThemeView.as_view(), name='theme_delete'),
    path('etiquettes/', views.etiquettes, name='etiquettes'),
    path('etiquettes/page/<int:key>', views.etiquettes_page, name='etiquettes_page'),
    path('etiquettes/alpha/', views.etiquettes_alpha, name='etiquettes_alpha'),
    re_path(r'^etiquettes/alpha/(?P<key>[A-Z\-])/$', views.etiquettes_alpha_page, name='etiquettes_alpha_page'),
    path('etiquettes/nuage/', cache_page(dcf)(views.etiquettes_nuage), name='etiquettes_nuage'),
    path('etiquette/<int:id>/', views.index_etiquette, name='index_etiquette'),
    path('etiquette/<int:id1>/<int:id2>/', views.index_etiquette_detail, name='index_etiquette_detail'),
    path('etiquette/<pk>/delete/', views.DeleteEtiquetteView.as_view(), name='etiquette_delete'),
    path('glossaire/', views.glossaire, name='glossaire'),
    re_path(r'^glossaire/(?P<key>[A-Z\-])/$', views.glossaire_page, name='glossaire_page'),
    path('glossaire/<int:id>/', views.entree_glossaire, name='entree_glossaire'),
    path('glossaire/search/<str:txt>/', views.recherche_glossaire, name='recherche_glossaire'),
    path('glossaire/<pk>/delete/', views.DeleteEntreeGlossaireView.as_view(), name='entree_glossaire_delete'),
    path('agenda/', views.agenda_current_month, name='agenda'),
    path('agenda/<int:year>/', cache_page(dcf)(views.agenda_year), name='agenda_year'),
    path('agenda/<int:year>/<int:month>/', views.agenda_month, name='agenda_month'),
    path('agenda/<int:year>/<int:month>/details/', views.agenda_month_details, name='agenda_month_details'),
    path('agenda/<int:year>/<int:month>/<int:day>/', views.entree_agenda, name='entree_agenda'),
    path('agenda/entree/<int:id>/', views.entree_agenda_pk, name='entree_agenda_pk'),
    path('agenda/entree/<pk>/pdf/', views.EntreeAgendaViewPDF.as_view(), name='entree_agenda_pdf'),
    path('agenda/entree/<pk>/delete/', views.DeleteEntreeAgendaView.as_view(), name='entree_agenda_delete'),
    path('agenda/entree/<pk>/inverser/', views.entree_agenda_invert_with, name='entree_agenda_invert_with'),
    path('agenda/inverser/', views.entree_agenda_invert, name='entree_agenda_invert'),
    path('agenda/sans-niveau/', views.agenda_sans_niveau, name='agenda_sans_niveau'),
    path('404/', views.page_not_found_view, name="page_not_found"),
    # pour ajouter et modifier les objets, on utilise un formulaire
    path('<str:classname>/add/', views.edit_object, name='object_add'),
    path('<str:classname>/<int:id>/change/', views.edit_object, name='object_change'),
    path('<str:classname>/<int:id>/duplicate/', views.duplicate_object, name='object_duplicate'),
    # pour ajouter des objets simples, on utilise une API (uniquement POST implémenté)
    path('<str:classname>/api/', views.rest_api, name='rest_api'),
    # pour les catégories simples, on propose la fusion
    path('<str:classname>/merge/', views.merge, name='merge'),
    path('modifications/', views.modifications, name='modifications'),
    path('modifications/page/<int:key>', views.modifications_page, name='modifications_page'),
    path('<str:classname>/modifications/', views.simple_modifications, name='simple_modifications'),
    path('<str:classname>/modifications/page/<int:key>', views.simple_modifications_page, name='simple_modifications_page'),
    path('liens-sortants/', views.liens_sortants, name='liens_sortants'),
    path('a-propos/', views.a_propos, name='a_propos'),
]

web/fichier/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone
from django.db.models.signals import pre_save, post_init
from django.db.models import Func, F, Value, Q
from django.db.models.functions import Concat, Right
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User
from django_better_admin_arrayfield.models.fields import ArrayField
import re
from django.utils.html import strip_tags
from django.utils.text import Truncator
from .utils import table, arrayToString, Agenda
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchHeadline
from django.contrib.postgres.aggregates.general import ArrayAgg
from sortedm2m.fields import SortedManyToManyField
from .utils import message_glossaire, message_sortable
import locale
from datetime import date, timedelta
from django.utils.translation import gettext as _


import logging
logger = logging.getLogger(__name__)


def build_list_urls(txt):
    return sorted(list(set([x[1] for x in re.findall(r"(^|\<p\>|[\n \"])(([\w]+?://[\w\#$%&~.\-;:=,?@\[\]+]*)(/[\w\#$%&~/.\-;:=,?@\[\]+]*)?)", txt)])))


def rechercher_nom_simple(search_text, classname):
    from django.contrib.postgres.search import SearchVector
    from django.contrib.postgres.search import SearchQuery

    if not search_text:
        return None

    search_vectors = SearchVector('nom', weight='A', config='french')
    search_query = SearchQuery(search_text, config='french')
    return classname.objects.annotate(search=search_vectors).filter(search=search_query). \
        annotate(nom_hl=SearchHeadline("nom",
                 search_query,
                 start_sel="<span class=\"highlight\">",
                 stop_sel="</span>",
                 highlight_all=True,
                 config='french'))


class EntetePage(models.Model):

    page = models.CharField(unique=True, max_length=32)
    texte = RichTextField(verbose_name="Texte de l'entête", config_name='main_ckeditor', blank=True)

    date_derniere_modification = models.DateTimeField(verbose_name="Dernière modification", auto_now=True)

    def save(self, *args, **kwargs):
        self.date_derniere_modification = timezone.now()
        super().save(*args, **kwargs)

    def url_name(self):
        return EntetePage.page_url_name(self.page)

    def url_parameters(self):
        return EntetePage.page_url_parameters(self.page)

    def get_absolute_url(self):
        return reverse(self.url_name(), args=self.url_parameters())

    def page_url_name(page_name):
        if page_name.startswith("agenda/"):
            return "fichier:agenda_month"
        elif page_name.startswith("agenda"):
            return "fichier:agenda"
        else:
            return "fichier:" + page_name

    def page_url_parameters(page_name):
        if page_name.startswith("agenda/"):
            return [int(x) for x in page_name.split("/")[1:3]]
        else:
            return []

    def edit_url(self):
        return reverse("fichier:object_change", kwargs={'classname': 'entete_page', 'id': self.pk})

    def create_url(page_name):
        return reverse("fichier:object_add", kwargs={'classname': 'entete_page'}) + "?page=" + page_name

    def get_nom_page(self):
        return EntetePage.nom_page(self.page)

    def nom_page(page):
        if page.startswith("agenda/") or page.startswith("agenda:"):
            elements = page.split("/")
            if len(elements) == 1:
                elements = page.split(":")
            mois = Agenda.month_name[int(elements[2])]
            annee = elements[1]
            if mois[0] in ['a', 'e', 'i', 'o', 'u']:
                return "du mois d'" + mois + " " + annee
            else:
                return "du mois de " + mois + " " + annee
        else:
            nom_page = {"index": "des fiches", "desk": "du desk", "categories": "des catégories",
                        "glossaire": "du glossaire", "accueil": "de l'accueil",
                        "themes": "des thèmes", "etiquettes": "des étiquettes", "agenda": "de l'agenda",
                        "liens_sortants": "des liens sortants"}
            return nom_page[page]

    def __str__(self):
        return "la page " + EntetePage.nom_page(self.page)

    def rechercher(search_text):
        from django.contrib.postgres.search import SearchVector
        from django.contrib.postgres.search import SearchQuery

        if not search_text:
            return None

        search_vectors = SearchVector('texte', weight='A', config='french')
        search_query = SearchQuery(search_text, config='french')
        return EntetePage.objects.annotate(search=search_vectors).filter(search=search_query). \
            annotate(texte_hl=SearchHeadline("texte",
                     search_query,
                     start_sel="<span class=\"highlight\">",
                     stop_sel="</span>",
                     max_fragments=50,
                     config='french'))


class Niveau(models.Model):

    class Applicabilite(models.TextChoices):
        A = 'A', "informatif"
        B = 'B', "pratique"
        C = 'C', "opérationnel"

        def couleur(appl):
            if appl == Niveau.Applicabilite.A:
                return Niveau.couleur_A
            elif appl == Niveau.Applicabilite.B:
                return Niveau.couleur_B
            else:
                return Niveau.couleur_C

        def nom(appl):
            if appl == Niveau.Applicabilite.A:
                return Niveau.Applicabilite.A.label
            elif appl == Niveau.Applicabilite.B:
                return Niveau.Applicabilite.B.label
            else:
                return Niveau.Applicabilite.C.label

    couleur_A = "#fdfbe9"
    couleur_B = "#ea841d"
    couleur_C = "#67b43f"

    ordre = models.IntegerField(verbose_name="Numéro", unique=True)
    code = models.CharField(verbose_name="Code", max_length=4, unique=True)
    nom = models.CharField(verbose_name="Nom", max_length=64)
    description = models.CharField(verbose_name="Description", max_length=256, blank=True, null=True)
    applicable = models.CharField(max_length=1, choices=Applicabilite.choices, default=Applicabilite.B)
    date_derniere_modification = models.DateTimeField(verbose_name="Dernière modification", auto_now=True)

    def delete(self, *args, **kwargs):
        self.update_associated_entries()
        super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        # update associated entries
        self.update_associated_entries()
        self.date_derniere_modification = timezone.now()
        super().save(*args, **kwargs)

    def couleur(self):
        return Niveau.Applicabilite.couleur(self.applicable)

    class Meta:
        verbose_name = "Niveau"
        verbose_name_plural = "Niveaux"

    def __str__(self):
        return " ".join(["{:02d}".format(self.ordre), self.code])

    def rechercher(search_text):
        return rechercher_nom_simple(search_text, Niveau)

    def associated_entries(self):
        result = []

        if self.id:
            # Liste des entrées d'agenda associées à cette catégorie
            result += Fiche.objects.filter(themes=self.id)

        return result

    def update_associated_entries(self):
        for e in self.associated_entries():
            e.date_demande_mise_a_jour = timezone.now()
            e.save()


class TypeCategorie(models.Model):
    nom = models.CharField(verbose_name="Nom du type de catégorie", max_length=64, unique=True)

    class Meta:
        verbose_name = "Type de catégorie"
        verbose_name_plural = "Types de catégorie"

    def __str__(self):
        return self.nom

    def description_longue(self):
        return self.nom


class Categorie(models.Model):
    code = models.CharField(verbose_name="Code de la catégorie", max_length=4, unique=True)
    nom = models.CharField(verbose_name="Nom de la catégorie", max_length=64)
    type_categorie = models.ForeignKey(TypeCategorie, verbose_name="Type de la catégorie", on_delete=models.SET_NULL, blank=True, null=True)
    is_biblio = models.BooleanField(verbose_name="Nécessite les champs de bibliographie", default=False)
    is_site = models.BooleanField(verbose_name="Nécessite les champs de site internet", default=False)
    is_film = models.BooleanField(verbose_name="Nécessite les champs d'un film", default=False)
    date_derniere_modification = models.DateTimeField(verbose_name="Dernière modification", auto_now=True)

    class Meta:
        verbose_name = "Catégorie"
        verbose_name_plural = "Catégories"

    def __str__(self):
        return self.code

    def get_absolute_url(self):
        return reverse('fichier:index_categorie', kwargs={'id': self.pk})

    def description_longue(self):
        return self.code + " — " + self.nom

    def rechercher(search_text):
        return rechercher_nom_simple(search_text, Categorie)

    def delete(self, *args, **kwargs):
        # update associated entries
        self.update_associated_entries()
        super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        # update associated entries
        self.update_associated_entries()
        self.date_derniere_modification = timezone.now()
        super().save(*args, **kwargs)

    def associated_entries(self):
        result = []

        if self.id:
            # Liste des entrées d'agenda associées à cette catégorie
            result += Fiche.objects.filter(Q(categorie1=self.id) | Q(categorie2=self.id) | Q(categorie3=self.id))

        return result

    def update_associated_entries(self):
        for e in self.associated_entries():
            e.date_demande_mise_a_jour = timezone.now()
            e.save()


class Auteur(models.Model):
    code = models.CharField(verbose_name="Code auteur", max_length=3)
    nom = models.CharField(verbose_name="Nom complet", max_length=64)

web/fichier/templates/fiches/agenda_month_pdf.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    {% load fichier_extras %}
    <title>Agenda 365 - {{ month|nom_mois_particule }} {{ year }}</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/page.css' %}">
    <link rel="stylesheet" href="{% static 'css/page_pdf.css' %}">
    <link rel="stylesheet" href="{% static 'css/contenu.css' %}">
</head>
<body class="A4_A5">
    <page size="A5" class="web premier_titre" layout="landscape">
        <div class="titre_large">
        {% include "fiches/entete_mois.html" with entete_mois_edit=0 %}
        </div>
    </page>
    {% for entree in object_list %}
        {% include "fiches/affichage_entree_agenda.html" with liens="" ephemeride=entree.to_ephemeride not_alone=1 %}
    {% endfor %}
</body>

web/fichier/templates/fiches/contenu_agenda.html
{% load fichier_extras %}


<div class="block center-cal">
    <div class="centered texte_court onlyweb">
        <h2 class="description">Texte court</h2>
        {% if entree.texte_court %}
        {{ entree.texte_court | ajouter_glossaire:True | safe }}
        {% else %}
         <em>texte à venir</em>
        {% endif %}
    </div>
    <div class="centered texte_long">
        <h2 class="description onlyweb">Texte long</h2>
        {% if entree.texte_long %}
        {{ entree.texte_long | ajouter_glossaire:True | safe }}
        {% else %}
        <em>texte à venir</em>
        {% endif %}
        </div>
    </div>


{% if entree.fiches_associees.all %}
<div class="block bottom-cal">
    <{{ hx }}>Pour prolonger la lecture&nbsp;:</{{ hx }}>
<ul>
{% for associee in entree.fiches_associees.all %}
    <li>Consulter <a class="internal" href="{% url 'fichier:detail' associee.id %}">la fiche {{ associee.titre_fiche }} {{ associee.sous_titre }}</a></li>
{% endfor %}
</ul>
</div>
{% endif %}

web/fichier/templates/fiches/critere.html
{% extends "fiches/page.html" %}

{% load fichier_extras %}

{% block entete_menu %}
{% with critere_name_pluriel as active_page %}
    {{ block.super }}
{% endwith %}
{% endblock %}



{% block title %}
Aidants 365 — {{ titre }} {{ visu }}
{% endblock %}

{% block content %}
    {% load fichier_extras %}
    <div class="block" id="entete">
        {% include "fiches/ajouter_critere.html" %}

        <h1>{{ titre }} {{ extension_titre }} {{ visu }} <span class="remarque">({% if nb_elements %}{{ elements.all.count }} entrées parmi {{ nb_elements }}{% else %}{{ elements.all.count }} entrées{% endif %})</span></h1>
 
        {% include "fiches/entete.html" %}

        <p>Afficher par&nbsp;:
        {% if visu_code == "basic" %} 
            <span class="active_visu">nombre de fiches</span>
        {% else %}
            {% with "fichier:"|add:critere_name_pluriel as template_name %}
            <a class="visu" href="{% url template_name %}">nombre de fiches</a>
            {% endwith %}
        {% endif %}
        {% if visu_code == "alpha" %} 
            <span class="active_visu">ordre alphabétique</span>
        {% else %}
            {% with "fichier:"|add:critere_name_pluriel|add:"_alpha" as template_name %}
            <a class="visu" href="{% url template_name %}">ordre alphabétique</a>
            {% endwith %}
        {% endif %}
            {% with "fichier:"|add:critere_name_pluriel|add:"_nuage"  as template_name %}
                {% if nom_humain_pluriel == "étiquettes" %}
                <a class="visu" href="{% url template_name %}">nuage d'{{ nom_humain_pluriel }}</a>
                {% else %}
                <a class="visu" href="{% url template_name %}">nuage de {{ nom_humain_pluriel }}</a>
                {% endif %}
        {% endwith %}
        </p>

        {% if key_alpha %}
            {% index_alpha key_alpha url_key_alpha %}
        {% endif %}

        {% if paginator %}
            {% index_paginator paginator p_id url_key_paginator %}
        {% endif %}
        </div>
    <div class="block">
        <p>On retrouve dans le tableau ci-dessous le nombre de fiches de chaque niveau (informatif, pratique, opérationnel), ainsi que le nombre total de fiches par {{ nom_humain }}.
        {% if key_alpha %}
        {% if elements.all.count == 0 %}
            Il n'y a pas de {{ nom_humain }}
         {% else %}
            Il y a  {% if elements.all.count == 1 %} un seul {{ nom_humain }} {% else %} {{ elements.all.count }} {{ nom_humain_pluriel }} {% endif %}
        {% endif %}
        commençant par 
            {% if key_alpha == "-" %}
                un caractère non alphabétique.
            {% else %}
                {{ key_alpha }}.
            {% endif %}
        {% endif %}</p>

        {% include "fiches/table_par_niveau.html" %}

    </div>

    {% if key_alpha or paginator %}
        <div class="block">
    {% if key_alpha %}
        {% index_alpha key_alpha url_key_alpha %}
    {% endif %}

    {% if paginator %}
        {% index_paginator paginator p_id url_key_paginator %}
    {% endif %}
    </div>
    {% endif %}
{% endblock %}

web/fichier/templates/fiches/desk.html
{% extends "fiches/page.html" %}

{% load fichier_extras %}

{% block entete_menu %}
{% with "desk" as active_page %}
    {{ block.super }}
{% endwith %}
{% endblock %}



{% block title %}
Le fichier Aidants365 — Desk
{% endblock %}




{% block entete %}
Desk
{% endblock %}

{% block content %}


    <div class="block" id="entete">
        <div class="lien_next bouton"><a title="ajouter un document" href="{%url 'fichier:object_add' 'document' %}">+ document</a></div>
        <h1>Desk</h1>

        {% include "fiches/entete.html" %}

    </div>
    <div class="block">
        {% if entrees %}

        <table>
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Date de création</th>
                    <th>Date de dernière modification</th>
                </tr>
            </thead>
            <tbody>
            {% for entree in entrees %}
                <tr>
                    <td><a href="{% url 'fichier:document' entree.id %}">{{ entree }}</a></td>
                    <td>{{ entree.date_creation }}</td> 
                    <td>{{ entree.date_derniere_modification }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucun document</p>
    {% endif %}
    </div>
</div>
{% endblock %}

web/fichier/templates/fiches/detail.html
{% extends "fiches/page.html" %}


{% block entete_header %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/page.css' %}">
<link rel="stylesheet" href="{% static 'css/page_html.css' %}">
<link rel="stylesheet" href="{% static 'css/pleine_page.css' %}">
<script src="{% static 'js/shortcut.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    function save_and_view(){
        document.getElementById('edit_button').click()
    }
    shortcut.add("Meta+E", save_and_view);
    shortcut.add("Ctrl+E", save_and_view);
</script>
{% endblock %}


{% block title %}
Projet365 — {{ fiche.titre_fiche }}
{% endblock %}

{% block content %}
    {% include "fiches/affichage_fiche.html" with liens="yes" %}
{% endblock %}

web/fichier/templates/fiches/index.html
{% extends "fiches/page.html" %}

{% block classe_principale %}detail_page{% endblock %}


{% load fichier_extras %}

{% block entete_menu %}
{% with "fiches" as active_page %}
    {{ block.super }}
{% endwith %}
{% endblock %}



{% block title %}
Le fichier Aidants365 — toutes les fiches
{% endblock %}




{% block entete %}
Toutes les fiches
{% endblock %}

{% block content %}


    <div class="block" id="entete">
        {% if "fichier.add_fiche" in perms %}
        <div class="lien_next bouton"><a title="ajouter une fiche" href="{%url 'fichier:object_add' 'fiche' %}">+ fiche</a></div>
        {% endif %}
        <h1>Toutes les fiches</h1>
        {% include "fiches/entete.html" %}
        <p>Vous pouvez <a class="bouton_inline" id="dl_pdf" href="/media/fiches.pdf">télécharger</a> un pdf contenant toutes les fiches. Ce document n'est assemblé qu'une fois par jour.</p>
        {% if "fichier.change_fiche" in perms %}
        <div class="suite"><a href="{% url 'fichier:simple_modifications' 'fiches' %}">dernières modifications ▸</a></div>
        {% endif %}

    </div>
    <div class="block">
        {% include "fiches/nuage.html" %}
        
        <div class="suite"><a href="{% url 'fichier:categories_alpha' %}">détail des catégories ▸</a></div>

    </div>
    <div class="block">
        {% if fiche_list %}
        {% regroup fiche_list|dictsort:"niveau.applicable" by niveau.get_applicable_display as niveau_list %}


        {% for niveau in niveau_list %}
            <h2>Fiches de niveau {{ niveau.grouper }}</h2>
            <ul class="no_puces">
            {% for fiche in niveau.list %}
                <li id="fiche{{ fiche.id }}">{{ fiche.niveau.couleur | carre_colore }} <a href="{% url 'fichier:index_detail' fiche.id %}">{{ fiche }}</a></li>
            {% endfor %}
            </ul>

        {% endfor %}
    {% else %}
        <p>Pas de fiche disponible.</p>
    {% endif %}
    </div>
</div>
<div id="dl_message">
    <div><p>Veuillez patienter pendant la fabrication du document...</p></div>
</div>
{% endblock %}

web/fichier/templates/fiches/titre_glossaire.html
<{{ niveau }}>Entrée glossaire&nbsp;: 
    {% if niveau == "h1" %}
        {{ entree.entree }}
    {% else %}
        <a href="{{ entree.get_absolute_url }}">{{ entree.entree }}</a>
    {% endif %}
     <a class="card_edit" id="edit_button" href="{% url 'fichier:object_change' 'glossaire' entree.id %}">éditer{% if shortcut %} <small>(ctrl+e){% endif %}</small></a>
     <a class="card_edit" id="duplicate_button" href="{% url 'fichier:object_duplicate' 'glossaire' entree.id %}">dupliquer</a>
     <a class="card_edit" id="delete_button" href="{% url 'fichier:entree_glossaire_delete' entree.id %}">supprimer</a>
    </{{ niveau }}>
    {% if entree.formes_alternatives %} 
<p><strong>{% if entree.formes_alternatives|length > 1 %}Formes alternatives{% else %}Forme alternative{% endif %}&nbsp;:</strong> 
    {% for fa in entree.formes_alternatives %}{% if not forloop.first %}, {% endif %}{{ fa }}{% endfor %}
    {% endif %}</p>

{% if motscles %}
<p><strong>Mot{% if motscles.all.count > 1%}s{% endif %}-clé{% if motscles.all.count > 1%}s{% endif %} similaire{% if motscles.all.count > 1%}s{% endif %}&nbsp;:</strong>
    {% for mc in motscles %}
    {% if not forloop.first %}, {% endif %}<a href="{{ mc.get_absolute_url }}">{{ mc }}</a>
    {% endfor %}
</p>

{% endif %}

<p><strong>Voir aussi&nbsp;:</strong>  <a href="{% url 'fichier:rechercher' %}?search={{ entree.entree }}">toutes les références à {{ entree.entree }}</a> dans le fichier Aidants365.</p>

{% if entree.date_derniere_modification %}
<div class="lien_next">
    Dernière modification&nbsp;: {{entree.date_derniere_modification }}
</div>
<div style="clear: both"></div>
{% endif %}